version: "3.0"
services:
  db:
    container_name: "db_mailing_service"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_mailing_service
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge