"""Init

Revision ID: d6ec248cc095
Revises: 
Create Date: 2024-01-30 00:51:57.769340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ec248cc095'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('operator_code', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_mailing', sa.DateTime(), nullable=False),
    sa.Column('stop_mailing', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('operator_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('status', sa.Enum('sent', 'not_sent', 'sending_error', name='sendingstatus'), nullable=False),
    sa.Column('id_mailing', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_mailing'], ['mailings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('mailings')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
