"""Made Message.operator_code is optional

Revision ID: a958230cdabd
Revises: d6ec248cc095
Create Date: 2024-01-31 16:00:03.690309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a958230cdabd'
down_revision: Union[str, None] = 'd6ec248cc095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailings', 'operator_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailings', 'operator_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
